sudo: required
services:
  - docker

before_install:
  - docker build -t narasimhakamath/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true narasimhakamath/react-test npm test

after_success:
  - docker build -t narasimhakamath/multi-client ./client
  - docker build -t narasimhakamath/multi-nginx ./nginx
  - docker build -t narasimhakamath/multi-server ./server
  - docker build -t narasimhakamath/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images to push to Docker Hub
  - docker push narasimhakamath/multi-client
  - docker push narasimhakamath/multi-nginx
  - docker push narasimhakamath/multi-server
  - docker push narasimhakamath/multi-worker
